<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Credit Note - Lead(s)</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 40px;
            line-height: 1.6;
            color: #333;
        }

        h1 {
            color: #0f66af;
            text-align: center;
            margin-bottom: 30px;
        }

        .container {
            max-width: 900px;
            margin: 0 auto;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .executive-info {
            background-color: #f8f9fa;
            border: 1px solid #e0e0e0;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 30px;
        }

        .vehicle-section {
            margin-bottom: 40px;
        }

        .vehicle-section h3 {
            color: #0f66af;
            border-bottom: 2px solid #0f66af;
            padding-bottom: 8px;
            margin-bottom: 15px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            font-size: 14px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #0f66af;
            color: white;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .print-btn {
            text-align: center;
            margin: 40px 0;
        }

        .page-break {
            page-break-before: always;
        }

        @media print {
            .no-print {
                display: none;
            }
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="header">
            <h1>Credit Note</h1>
            <p>Generated by: {{ $distributor->name }} on {{ now()->format('d M Y') }}</p>
        </div>

        <!-- Executive & Lead Info (sirf ek baar) -->
        @if($details->isNotEmpty())
            @php $firstDetail = $details->first(); @endphp
            <div class="executive-info">
                <h3>Executive & Lead Information</h3>
                <p><strong>Executive:</strong> {{ $firstDetail->lead->executive->name ?? 'N/A' }}</p>
                <p><strong>Lead ID:</strong>
                    <td>{{ $firstDetail->lead_no ?? 'N/A' }}</td>
                </p>
                <p><strong>Customer:</strong> {{ $firstDetail->lead->customer_name }} ({{ $firstDetail->lead->phone_no }})
                </p>
                <p><strong>Dealer:</strong> {{ $firstDetail->lead->dealer->name ?? 'N/A' }}</p>
            </div>
        @endif

        <!-- Vehicle Details -->
        @foreach($details as $index => $detail)
            <div class="vehicle-section">
                <h3>Vehicle {{ $index + 1 }} Details</h3>
                <p><strong>Verified Date:</strong>
                    {{ $detail->verified_at ? \Carbon\Carbon::parse($detail->verified_at)->format('d M Y') : 'N/A' }}</p>
                <p><strong>Invoice No:</strong> {{ $detail->invoice_no ?? 'N/A' }}</p>

                <table>
                    <tr>
                        <th>Brand</th>
                        <th>Variant</th>
                        <th>Color</th>
                        <th>Quantity</th>
                        <th>Commission</th>
                    </tr>
                    <tr>
                        <td>{{ $detail->brand->name ?? 'N/A' }}</td>
                        <td>{{ $detail->variant->name ?? 'N/A' }}</td>
                        <td>{{ $detail->color->name ?? 'N/A' }}</td>
                        <td>{{ $detail->vehicle_qty }}</td>
                        <td>${{ number_format($detail->variant->commission ?? 0, 2) }}</td>
                    </tr>
                </table>

                @if($detail->uploaded_invoice)
                    <p style="margin-top: 15px;">
                        <strong>Uploaded Invoice:</strong>
                        <a href="{{ url(Storage::url($detail->uploaded_invoice)) }}" target="_blank">View/Download</a>
                    </p>
                @endif
            </div>

            @if($index < $details->count() - 1)
                <div class="page-break"></div>
            @endif
        @endforeach

        <div class="print-btn no-print">
            <button onclick="window.print()" class="btn btn-primary btn-lg">
                <i class="bi bi-printer"></i> Print / Save as PDF
            </button>
        </div>
    </div>
</body>

</html>
