<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice Note - Lead(s)</title>
    <style>
        body {
            font-family: 'Arial', 'Helvetica', sans-serif;
            margin: 40px;
            line-height: 1.6;
            color: #333;
            background-color: #fff;
        }

        .container {
            max-width: 900px;
            margin: 0 auto;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .header h1 {
            color: #0f66af;
            font-size: 28px;
            margin: 0 0 10px;
        }

        .header p {
            color: #555;
            font-size: 14px;
            margin: 0;
        }

        .customer-info {
            background-color: #f8f9fa;
            border: 1px solid #e0e0e0;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 30px;
        }

        .customer-info h3 {
            color: #0f66af;
            margin-top: 0;
            font-size: 20px;
        }

        .customer-info p {
            margin: 8px 0;
            font-size: 15px;
        }

        .vehicle-section {
            margin-bottom: 40px;
        }

        .vehicle-section h3 {
            color: #0f66af;
            border-bottom: 2px solid #0f66af;
            padding-bottom: 8px;
            margin-bottom: 15px;
            font-size: 22px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            font-size: 14px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #0f66af;
            color: white;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .invoice-link {
            color: #0f66af;
            text-decoration: none;
            font-weight: bold;
        }

        .invoice-link:hover {
            text-decoration: underline;
        }

        .footer {
            text-align: center;
            margin-top: 40px;
            color: #555;
            font-size: 13px;
        }

        .print-btn {
            text-align: center;
            margin: 40px 0;
        }

        .no-print {
            display: block;
        }

        @media print {
            .no-print {
                display: none;
            }
            body { margin: 0; }
            .container { max-width: 100%; }
        }

        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Bajaj Distributor Invoice Note</h1>
            <p>Generated by: {{ $distributor->name }} on {{ now()->format('d M Y') }}</p>
        </div>

        <!-- Customer Details (Show once for the first lead) -->
        @if($details->isNotEmpty())
            @php $firstDetail = $details->first(); @endphp
            <div class="customer-info">
                <h3>Customer & Lead Information</h3>
                <p><strong>Lead ID:</strong> #{{ str_pad($firstDetail->lead->id, 6, '0', STR_PAD_LEFT) }}</p>
                <p><strong>Customer Name:</strong> {{ $firstDetail->lead->customer_name }}</p>
                <p><strong>Phone No:</strong> {{ $firstDetail->lead->phone_no }}</p>
                <p><strong>Dealer:</strong> {{ $firstDetail->lead->dealer->name ?? 'N/A' }}</p>
                <p><strong>Distributor:</strong> {{ $distributor->name }}</p>
            </div>
        @endif

        <!-- Vehicle Details -->
        @foreach($details as $index => $detail)
            <div class="vehicle-section">
                <h3>Vehicle {{ $index + 1 }} Details</h3>
                <p><strong>Verified Date:</strong> {{ $detail->verified_at ? \Carbon\Carbon::parse($detail->verified_at)->format('d M Y') : 'N/A' }}</p>
                <p><strong>Invoice No:</strong> {{ $detail->invoice_no ?? 'N/A' }}</p>

                <table>
                    <tr>
                        <th>Brand</th>
                        <th>Variant</th>
                        <th>Color</th>
                        <th>Quantity</th>
                        <th>Total Price</th>
                    </tr>
                    <tr>
                        <td>{{ $detail->brand->name ?? 'N/A' }}</td>
                        <td>{{ $detail->variant->name ?? 'N/A' }}</td>
                        <td>{{ $detail->color->name ?? 'N/A' }}</td>
                        <td>{{ $detail->vehicle_qty }}</td>
                        <td>${{ number_format($detail->total_price ?? 0, 2) }}</td>
                    </tr>
                </table>

                @if($detail->uploaded_invoice)
                    <p style="margin-top: 15px;">
                        <strong>Uploaded Invoice:</strong>
                        <a href="{{ url(Storage::url($detail->uploaded_invoice)) }}" class="invoice-link" target="_blank">
                            View/Download Invoice
                        </a>
                    </p>
                @endif
            </div>

            @if($index < $details->count() - 1)
                <div class="page-break"></div>
            @endif
        @endforeach

        <div class="footer">
            <p>Generated on: {{ now()->format('d M Y') }} by {{ $distributor->name }}</p>
        </div>

        <div class="print-btn no-print">
            <button onclick="window.print()" class="btn btn-primary btn-lg">
                <i class="bi bi-printer"></i> Print / Save as PDF
            </button>
        </div>
    </div>
</body>
</html>
